### ISSUE TITLE
Twisted Integration

### ISSUE THREAD

**Issue by Highersocieties** [exxeleron/qPython#53]
Hi there!

I'm currently trying to get the Twisted integration example you provided to work, but I', running into a few issues.
First of all: when I'm trying to connect to kdb the line `self.transport.write(self.credentials + '\3\0')` throws an TypeError telling me the "Data must not be unicode". So I tried changing it to `self.transport.write(str(self.credentials + '\0').encode("utf-8"))` (not the most sexy solution, I know) and the error disappeared... But as it usually goes, another showed up.
This time a TypeError with cause "not all arguments converted during string formatting" popped up, and I do not seem to be able to find where It is coming from. Is this about data that's coming from kdb that is not being converted, or outgoing data?

The kdb database I'm currently working with has no users so I did not provide a username and password --> `factory = IPCClientFactory('', '', onConnectSuccess, onConnectFail, onMessage, onError)`.

Could that be in the way of succes? I'm a bit clueless..

Thanks in advance!

**Comment by Highersocieties** [comment]
Regular string injection like so: `"%s\0" % self.credentials' worked.. My bad...

**Comment by maciejlach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a User I would like to share a video of my choice on social media so that I am able to recommend it to my followers or leave social commentary](https://trello.com/c/sOfvZ3yy/12-as-a-user-i-would-like-to-share-a-video-of-my-choice-on-social-media-so-that-i-am-able-to-recommend-it-to-my-followers-or-leave)
